name: cicd pipeline

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: agen-1
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: setup-NodeJs
        uses: actions/setup-node@v4
        with: 
           node-version: '23'

      - name: frontend syntax check 
        run: |
         cd client
         find . -name "*.js" -exec node --check {} +

      - name: backend syntax check 
        run: |
         cd api
         find . -name "*.js" -exec node --check {} + 

  

    

      


          
          
          
        
